const RANKS=['A','K','Q','J','T','9','8','7','6','5','4','3','2'];
const COLORS=['#ef4444','#f97316','#eab308','#22c55e','#14b8a6','#06b6d4','#3b82f6','#6366f1','#8b5cf6','#ec4899','#64748b','#111827','#F8F8F6'];
const DB_NAME='PokerRangeDrill',DB_VERSION=1;let db;
const state={view:'ranges',editing:null,selectedCells:new Set(),drill:null};
let gridPointerActive=false,gridSelectionMode=true,lastTouchedHand=null;
function uid(prefix){return prefix+'_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,7)}
function handAt(r,c){if(r===c)return RANKS[r]+RANKS[c];return r<c?RANKS[r]+RANKS[c]+'s':RANKS[c]+RANKS[r]+'o'}
function allHands(){const a=[];for(let r=0;r<13;r++)for(let c=0;c<13;c++)a.push(handAt(r,c));return a}
function openDB(){return new Promise((res,rej)=>{const req=indexedDB.open(DB_NAME,DB_VERSION);req.onupgradeneeded=()=>{const d=req.result;if(!d.objectStoreNames.contains('ranges'))d.createObjectStore('ranges',{keyPath:'id'});if(!d.objectStoreNames.contains('history'))d.createObjectStore('history',{keyPath:'id'})};req.onsuccess=()=>{db=req.result;res()};req.onerror=()=>rej(req.error)})}
function tx(store,mode='readonly'){return db.transaction(store,mode).objectStore(store)}
function getRanges(){return new Promise((res,rej)=>{const q=tx('ranges').getAll();q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
function putRange(r){return new Promise((res,rej)=>{const q=tx('ranges','readwrite').put(r);q.onsuccess=()=>res();q.onerror=()=>rej(q.error)})}
function delRange(id){return new Promise((res,rej)=>{const q=tx('ranges','readwrite').delete(id);q.onsuccess=()=>res();q.onerror=()=>rej(q.error)})}
function getHistory(){return new Promise((res,rej)=>{const q=tx('history').getAll();q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
function addHistory(h){return new Promise((res,rej)=>{const q=tx('history','readwrite').put(h);q.onsuccess=()=>res();q.onerror=()=>rej(q.error)})}
function deleteHistory(id){return new Promise((res,rej)=>{const q=tx('history','readwrite').delete(id);q.onsuccess=()=>res();q.onerror=()=>rej(q.error)})}
async function trimHistory(){const hs=(await getHistory()).sort((a,b)=>new Date(b.date)-new Date(a.date));for(const h of hs.slice(5))await deleteHistory(h.id)}
async function init(){await openDB();if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});render()}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function nav(v){state.view=v;state.editing=null;state.selectedCells.clear();render()}
function render(){document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.nav===state.view||state.view==='editor'&&b.dataset.nav==='ranges'||['question','result','setup'].includes(state.view)&&b.dataset.nav==='drill'));const app=document.getElementById('app');if(state.view==='ranges')renderRanges(app);else if(state.view==='editor')renderEditor(app);else if(state.view==='setup')renderSetup(app);else renderDrill(app)}
async function renderRanges(app){const rs=await getRanges(),hs=(await getHistory()).sort((a,b)=>new Date(b.date)-new Date(a.date));app.innerHTML=`<main class="app"><div class="top"><h1>Mes ranges</h1><button class="btn" id="newRange">+ Créer</button></div>${rs.length?rs.map(r=>`<section class="card range-card"><div class="range-main"><div class="range-name">${esc(r.nom)}</div><div class="chips">${r.informations?.position?`<span class="chip">${esc(r.informations.position)}</span>`:''}${r.informations?.stack?`<span class="chip">${esc(r.informations.stack)}</span>`:''}${r.informations?.situation?`<span class="chip">${esc(r.informations.situation)}</span>`:''}<span class="chip">${Object.values(r.mains).filter(x=>x.length).length}/169</span></div></div><div class="actions"><button class="btn secondary edit" data-id="${r.id}">Modifier</button><button class="btn danger delete" data-id="${r.id}">×</button></div></section>`).join(''):`<div class="card empty"><div class="big">Aucune range</div><p class="muted">Crée ta première range pour commencer tes drills.</p><button class="btn" id="emptyNew">Créer une range</button></div>`}<div class="card"><div class="section-title" style="margin-top:0">Historique</div>${hs.length?hs.map(h=>{const pct=Math.round(h.score/h.total*100);const d=new Date(h.date);return `<div class="history-item"><div class="history-main"><div><b>${d.toLocaleDateString('fr-FR')} à ${d.toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}</b><br><span class="muted">${h.total} mains</span></div><div class="history-score">${h.score}/${h.total}</div></div><div><b>${pct} % de réussite</b></div></div>`}).join(''):'<div class="muted">Aucun drill réalisé pour le moment.</div>'}</div></main>`;document.getElementById('newRange')?.addEventListener('click',()=>openEditor());document.getElementById('emptyNew')?.addEventListener('click',()=>openEditor());app.querySelectorAll('.edit').forEach(b=>b.onclick=async()=>openEditor((await getRanges()).find(r=>r.id===b.dataset.id)));app.querySelectorAll('.delete').forEach(b=>b.onclick=async()=>{if(confirm('Supprimer cette range ?')){await delRange(b.dataset.id);render()}})}
function blankRange(){return{id:uid('range'),nom:'',informations:{position:'',stack:'',situation:''},etiquettes:[],mains:Object.fromEntries(allHands().map(h=>[h,[]]))}}
async function openEditor(range){state.editing=range?structuredClone(range):blankRange();state.selectedCells.clear();state.view='editor';render()}
function syncEditorFields(){const r=state.editing;if(!r)return;r.nom=document.getElementById('name')?.value??r.nom;r.informations.position=document.getElementById('position')?.value??r.informations.position;r.informations.stack=document.getElementById('stack')?.value??r.informations.stack;r.informations.situation=document.getElementById('situation')?.value??r.informations.situation}
function renderEditor(app){const r=state.editing;app.innerHTML=`<main class="app"><div class="top"><button class="btn secondary" id="back">← Retour</button><h1>${r.nom?'Modifier':'Nouvelle range'}</h1><span></span></div><div class="card"><div class="field"><label>Nom de la range *</label><input class="input" id="name" value="${esc(r.nom)}" placeholder="Ex. BTN Open"></div><div class="field"><label>Position</label><input class="input" id="position" value="${esc(r.informations.position)}" placeholder="BTN, UTG, BB..."></div><div class="field"><label>Stack</label><input class="input" id="stack" value="${esc(r.informations.stack)}" placeholder="40 BB"></div><div class="field"><label>Situation</label><input class="input" id="situation" value="${esc(r.informations.situation)}" placeholder="Open, vs BTN, 3-bet..."></div></div><div class="card"><div class="section-title" style="margin-top:0">Étiquettes / actions</div><div class="labels">${r.etiquettes.map(l=>`<div class="label-row"><i class="swatch" style="background:${l.couleur}"></i><span class="grow">${esc(l.nom)}</span><button class="btn secondary rename" data-id="${l.id}">Modifier</button><button class="btn danger remove-label" data-id="${l.id}">×</button></div>`).join('')||'<span class="muted">Crée des étiquettes comme Fold, Call, Raise, All-in…</span>'}</div><button class="btn secondary" id="addLabel" style="margin-top:10px">+ Ajouter une étiquette</button></div><div class="card"><div class="section-title" style="margin-top:0">Matrice 13 × 13</div><p class="muted">Maintiens le doigt (ou le clic) et glisse pour sélectionner plusieurs mains.</p><div class="matrix-wrap" id="matrix-wrap"><table class="matrix" id="range-grid"><tbody>${Array.from({length:13},(_,row)=>`<tr>${Array.from({length:13},(_,col)=>cellHTML(r,row,col)).join('')}</tr>`).join('')}</tbody></table></div><div class="selected-count" id="selected-count">${state.selectedCells.size} main${state.selectedCells.size>1?'s':''} sélectionnée${state.selectedCells.size>1?'s':''}</div><div class="toolbar"><button class="btn secondary" id="clearSel">Désélectionner</button></div><div class="matrix-labels">${r.etiquettes.map(l=>`<span><i style="background:${l.couleur}"></i>${esc(l.nom)}</span>`).join('')}</div></div><div class="card"><div class="section-title" style="margin-top:0">Appliquer une étiquette aux mains sélectionnées</div><div class="toolbar">${r.etiquettes.map(l=>`<button class="btn secondary assign" data-label="${l.id}">Appliquer : ${esc(l.nom)}</button>`).join('')||'<span class="muted">Ajoute d’abord une étiquette.</span>'}</div></div><div class="sticky"><button class="btn" id="save" style="width:100%">Enregistrer la range</button></div></main>`;
document.getElementById('back').onclick=()=>nav('ranges');document.getElementById('addLabel').onclick=()=>{syncEditorFields();labelModal()};document.getElementById('clearSel').onclick=()=>{state.selectedCells.clear();updateSelectedCount()};document.getElementById('save').onclick=saveRange;app.querySelectorAll('.remove-label').forEach(b=>b.onclick=()=>{syncEditorFields();r.etiquettes=r.etiquettes.filter(l=>l.id!==b.dataset.id);for(const h of allHands())r.mains[h]=r.mains[h].filter(x=>x!==b.dataset.id);render()});app.querySelectorAll('.rename').forEach(b=>b.onclick=()=>{syncEditorFields();labelModal(r.etiquettes.find(l=>l.id===b.dataset.id))});app.querySelectorAll('.assign').forEach(b=>b.onclick=()=>applyLabel(b.dataset.label));bindGridPointerEvents();}
function cellHTML(r,row,col){const h=handAt(row,col),ids=r.mains[h]||[],labels=ids.map(id=>r.etiquettes.find(l=>l.id===id)).filter(Boolean),style=labels.length===1?`<i class="single" style="background:${labels[0].couleur}"></i>`:labels.length===2?`<i class="split"><i style="background:${labels[0].couleur}"></i><i style="background:${labels[1].couleur}"></i></i>`:'';return `<td><button class="cell ${state.selectedCells.has(h)?'selected':''}" data-hand="${h}" type="button">${style}<span>${h}</span></button></td>`}
function bindGridPointerEvents(){const grid=document.getElementById('range-grid');if(!grid)return;grid.onpointerdown=gridPointerDown;grid.onpointermove=gridPointerMove;grid.onpointerup=gridPointerUp;grid.onpointercancel=gridPointerUp;grid.onpointerleave=()=>{};grid.oncontextmenu=e=>e.preventDefault()}
function cellFromPoint(x,y){const el=document.elementFromPoint(x,y);return el?.closest?.('.cell')||null}
function gridPointerDown(e){const cell=cellFromPoint(e.clientX,e.clientY);if(!cell)return;e.preventDefault();gridPointerActive=true;gridSelectionMode=!state.selectedCells.has(cell.dataset.hand);lastTouchedHand=null;selectGridCell(cell);try{e.currentTarget.setPointerCapture(e.pointerId)}catch(_) {}}
function gridPointerMove(e){if(!gridPointerActive)return;e.preventDefault();const cell=cellFromPoint(e.clientX,e.clientY);if(cell)selectGridCell(cell)}
function gridPointerUp(e){if(!gridPointerActive)return;e.preventDefault();gridPointerActive=false;lastTouchedHand=null;try{e.currentTarget.releasePointerCapture(e.pointerId)}catch(_) {}}
function selectGridCell(cell){const h=cell.dataset.hand;if(!h||h===lastTouchedHand)return;lastTouchedHand=h;if(gridSelectionMode)state.selectedCells.add(h);else state.selectedCells.delete(h);cell.classList.toggle('selected',gridSelectionMode);updateSelectedCount()}
function updateSelectedCount(){const el=document.getElementById('selected-count');if(el)el.textContent=`${state.selectedCells.size} main${state.selectedCells.size>1?'s':''} sélectionnée${state.selectedCells.size>1?'s':''}`}
function labelModal(existing){const r=state.editing;let color=existing?.couleur||COLORS[r.etiquettes.length%COLORS.length];document.getElementById('modal-root').innerHTML=`<div class="modal-backdrop"><div class="modal"><h2>${existing?'Modifier':'Nouvelle'} étiquette</h2><div class="field"><label>Nom</label><input class="input" id="labelName" value="${esc(existing?.nom||'')}" placeholder="Raise, Fold, All-in..."></div><div class="field"><label>Couleur</label><div class="color-grid">${COLORS.map(c=>`<button type="button" class="color-choice ${c===color?'selected':''}" data-color="${c}" style="background:${c}"></button>`).join('')}</div></div><div class="toolbar"><button class="btn secondary" id="cancel">Annuler</button><button class="btn" id="ok">Enregistrer</button></div></div></div>`;document.querySelectorAll('.color-choice').forEach(b=>b.onclick=()=>{color=b.dataset.color;document.querySelectorAll('.color-choice').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});document.getElementById('cancel').onclick=()=>document.getElementById('modal-root').innerHTML='';document.getElementById('ok').onclick=()=>{const n=document.getElementById('labelName').value.trim();if(!n)return;if(existing){existing.nom=n;existing.couleur=color}else r.etiquettes.push({id:uid('label'),nom:n,couleur:color});document.getElementById('modal-root').innerHTML='';render()}}
function applyLabel(id){const r=state.editing;syncEditorFields();for(const h of state.selectedCells){let a=r.mains[h]||[];if(a.includes(id))a=a.filter(x=>x!==id);else if(a.length<2)a=[...a,id];r.mains[h]=a}state.selectedCells.clear();render()}
async function saveRange(){syncEditorFields();const r=state.editing;if(!r.nom){alert('Donne un nom à la range.');return}await putRange(r);state.view='ranges';state.editing=null;render()}
function renderSetup(app){app.innerHTML=`<main class="app"><div class="top"><h1>Nouveau drill</h1></div><div class="card"><div class="section-title" style="margin-top:0">1. Choisir les ranges</div><div id="rangeChoices" class="muted">Chargement...</div></div><div class="card"><div class="section-title" style="margin-top:0">2. Nombre de mains</div><div class="toolbar">${[10,20,30,50,100].map(n=>`<button class="btn secondary len" data-n="${n}">${n}</button>`).join('')}</div></div><div class="sticky"><button class="btn" id="start" style="width:100%">Commencer</button></div></main>`;getRanges().then(rs=>{const box=document.getElementById('rangeChoices');if(!box)return;box.innerHTML=rs.length?rs.map(r=>`<label class="check-row"><input type="checkbox" class="range-check" value="${r.id}"><span class="grow"><b>${esc(r.nom)}</b><br><small class="muted">${Object.values(r.mains).filter(x=>x.length).length}/169 définies</small></span></label>`).join(''):'<div class="notice">Crée au moins une range avant de lancer un drill.</div>'});let len=20;app.querySelectorAll('.len').forEach(b=>b.onclick=()=>{len=+b.dataset.n;app.querySelectorAll('.len').forEach(x=>x.classList.add('secondary'));b.classList.remove('secondary')});document.getElementById('start').onclick=async()=>{const rs=await getRanges(),ids=[...document.querySelectorAll('.range-check:checked')].map(x=>x.value),sel=rs.filter(r=>ids.includes(r.id));if(!sel.length){alert('Sélectionne au moins une range.');return}const situations=buildSituations(sel);if(!situations.fold.length||!situations.nonFold.length){alert('Pour respecter le ratio 30/70, les ranges sélectionnées doivent contenir au moins une situation Fold et une situation Non-Fold définies.');return}state.drill={ranges:sel,questions:makeQuestions(situations,len),index:0,score:0,answers:[]};state.view='question';render()}}
function isFoldOnly(r,h){const ids=r.mains[h]||[];if(!ids.length)return false;return ids.every(id=>{const l=r.etiquettes.find(x=>x.id===id);return l&&l.nom.trim().toLowerCase()==='fold'})}
function buildSituations(rs){const fold=[],nonFold=[];for(const r of rs)for(const h of allHands()){if(!(r.mains[h]||[]).length)continue;const labels=(r.mains[h]||[]).map(id=>r.etiquettes.find(l=>l.id===id)).filter(Boolean);const s={rangeId:r.id,range:r,main:h,labels};(isFoldOnly(r,h)?fold:nonFold).push(s)}return{fold,nonFold}}
function sample(arr,n){const pool=[...arr],out=[];for(let i=0;i<n;i++){if(!pool.length)pool.push(...arr);const j=Math.floor(Math.random()*pool.length);out.push(pool.splice(j,1)[0])}return out}
function makeQuestions(s,len){const foldCount=Math.round(len*.3),nonFoldCount=len-foldCount;const q=[...sample(s.fold,foldCount),...sample(s.nonFold,nonFoldCount)];for(let i=q.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[q[i],q[j]]=[q[j],q[i]]}return q}
function renderDrill(app){const d=state.drill;if(!d){renderSetup(app);return}if(state.view==='result'){renderResult(app);return}const q=d.questions[d.index],multi=d.ranges.length>1,optionMap=new Map();for(const r of d.ranges)for(const l of r.etiquettes)optionMap.set(l.nom.trim(),l.nom.trim());const opts=[...optionMap.values()];for(let i=opts.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[opts[i],opts[j]]=[opts[j],opts[i]]}app.innerHTML=`<main class="app"><div class="muted">Question ${d.index+1} / ${d.questions.length}</div><div class="progress"><i style="width:${(d.index/d.questions.length)*100}%"></i></div>${multi?`<div class="context">${esc(q.range.nom)}</div>`:''}<div class="drill-hand">${q.main}</div><div class="answers">${opts.map(o=>{const l=q.range.etiquettes.find(x=>x.nom.trim()===o);return `<button class="btn answer" data-answer="${esc(o)}" style="--answer-border:${esc(l?.couleur||'#d7d7d1')}">${esc(o)}</button>`}).join('')}</div><div id="feedback"></div></main>`;app.querySelectorAll('.answer').forEach(b=>b.onclick=()=>answer(q,b.dataset.answer))}
function answer(q,ans){const good=q.labels.some(l=>l.nom.trim()===ans),d=state.drill;if(good)d.score++;d.answers.push({rangeId:q.rangeId,main:q.main,answer:ans,correct:good,correctAnswers:q.labels.map(l=>l.nom)});document.querySelectorAll('.answer').forEach(b=>b.disabled=true);const f=document.getElementById('feedback');f.innerHTML=`<div class="feedback ${good?'correct':'wrong'}"><b>${good?'✓ Correct':'✗ Incorrect'}</b><br>Bonne réponse : <b>${esc(q.labels.map(l=>l.nom).join(' + '))}</b></div><button class="btn" id="next" style="width:100%">${d.index+1<d.questions.length?'Suivant':'Voir le résultat'}</button>`;document.getElementById('next').onclick=()=>{if(d.index+1<d.questions.length){d.index++;state.view='question';render()}else finishDrill()}}
async function finishDrill(){const d=state.drill;await addHistory({id:uid('drill'),date:new Date().toISOString(),score:d.score,total:d.questions.length,answers:d.answers,ranges:d.ranges.map(r=>r.id)});await trimHistory();state.view='result';render()}
function renderResult(app){const d=state.drill,pct=Math.round(d.score/d.questions.length*100);app.innerHTML=`<main class="app"><div class="card result"><div class="muted">Drill terminé</div><div class="score">${pct}%</div><div class="big">${d.score} / ${d.questions.length}</div><p><b>${pct} % de réussite</b></p><p>${d.questions.length-d.score} erreur${d.questions.length-d.score>1?'s':''}</p></div><button class="btn" id="retry" style="width:100%;margin-bottom:9px">Refaire le drill</button><button class="btn secondary" id="home" style="width:100%">Retour aux ranges</button></main>`;document.getElementById('retry').onclick=()=>{const s=buildSituations(d.ranges);d.questions=makeQuestions(s,d.questions.length);d.index=0;d.score=0;d.answers=[];state.view='question';render()};document.getElementById('home').onclick=()=>nav('ranges')}
document.addEventListener('click',e=>{const n=e.target.closest('[data-nav]');if(n)nav(n.dataset.nav)});document.getElementById('app').addEventListener('pointerdown',e=>{if(e.target.closest('.matrix-wrap'))e.preventDefault()},{passive:false});
init().catch(e=>{document.getElementById('app').innerHTML='<main class="app"><div class="card"><b>Erreur de démarrage.</b><p>Ton navigateur ne semble pas autoriser IndexedDB.</p></div></main>';console.error(e)});
